#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

#define ERROR_FILE "../res/text/errors.txt"

#define INVALID_KEY_ERROR 1

#define VALUE_OUT_OF_BOUND_ERROR 2
#define INVALID_INPUT_ERROR 3

#define DUPLICATE_USERNAME_ERROR 5
#define INVALID_USERNAME_ERROR 4

#define ALLOCATION_ERROR 6
#define STRING_ALLOCATION_ERROR 7

#define INVALID_FILENAME_ERROR 8
#define FILE_NOT_WRITABLE_ERROR 9
#define FILE_NOT_READABLE_ERROR 10

#define CALL_STACK_OVERFLOW_ERROR 11
#define CALL_STACK_UNDERFLOW_ERROR 12

void print_err(const int index);
void throw_err(const int index);

#endif  // !ERROR_HANDLING_H
