#!/bin/sh
source "$(dirname "$0")/_/husky.sh"

# check diff
function check() {
    local name="$code ./$1 \e[0m"

    printf "\n \e[1;34m\e[0m  Checking $name for changes\n"
    if git diff --quiet --exit-code ./$1; then
        printf " \e[1;32m\e[0m  No changes detected to $name since last commit\n"
    else
        printf " \e[1;33m\e[0m  Detected changes to $name since last commit\n"
        printf " \e[1;35m\e[0m  Traking and committing changes...\n "
        git add ./$1
        git commit -m "feat(auto): :robot:  update \`./$1\`"

    fi
    return
}

# generate and commit changelog automatically
function changelog() {
    local name="$code ./CHANGELOG.md \e[0m"
    printf "\n \e[1;35m\e[0m  Generating $name"
    git cliff --output ./CHANGELOG.md
    return
}

function main() {
    declare code="\e[38;2;237;86;122;48;2;60;60;60m"

    check ".vscode/*"
    changelog
    check "CHANGELOG.md"

    printf "\n \e[1;32m\e[0m  All done!\n"
    return
}

main
