name: Build and Deploy with MkDocs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Cache stuff
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Material for MkDocs
        run: >-
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Install MkDocs plugins
        run: >-
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pillow cairosvg
          pip install mkdocs-glightbox
      - name: Deploy site
        run: mkdocs gh-deploy --force
